### PR TITLE
Better embark--display-string

### PR DESCRIPTION
**Pull request by minad**
Taken from vertico--display-string. Inherit face properties. To observe the improvement run consult-line in an Org buffer with TODOs and with org-modern-mode enabled and collect a snapshot. The TODO properties added by org-modern-mode are not displayed nicely otherwise.

### CODE REVIEW

**Comment by oantolin** [comment]
So this is something that hasn't hit Vertico yet, right? Because I see the same slightly incorrect display of TODOs in Vertico right now.

**Comment by oantolin** [comment]
Ah, I see you fixed this just 6 hours ago, it'll land pretty soon.

**Comment by oantolin** [comment]
Ooh, this is much nicer, thanks!

**Comment by minad** [comment]
Thanks for merging. This is most likely still not strictly correct, but the function is supposed to return a display string approximation only, which works in most common scenarios.

**Comment by oantolin** [comment]
The slightly wrong display of TODOs is really weird, I see the OD in the right font and the T and final O without any styling. Why is that?

**Comment by oantolin** [comment]
image

**Comment by minad** [comment]
The reason is that org-modern attaches a display property "T" -> " T" to the first character. This way org-modern fakes additional padding for the labels to make them more pretty. The face property of the displayed string however is supposed to be inherited from the original text.

**Comment by oantolin** [comment]
Ah, I see. And the same goes for the final "O".

**Comment by minad** [comment]
I could have also fixed this in org-modern to some extent, but I decided that is preferable to make `vertico--display-string` better. The`display` string property also had the issue that completion style faces were lost. This is not the case anymore with this change.

**Pull request merged**
