### PR TITLE
Add embark-bindings command

### PR DESCRIPTION
**Pull request by minad**
As discussed in #186 and #190. We get the command in 10 lines of code. I think that's worth it :)

### CODE REVIEW

**Comment by oantolin** [comment]
I was thinking of how to do this with a single command, but I guess this much easier. The PR looks good to me now, is there anything else you wanted to do first?

**Comment by minad** [comment]
I have a few minor improvements. I ping you again, when I think it is ready.

**Comment by oantolin** [comment]
OK.

**Comment by minad** [comment]
Okay, I think it is good like this now.

**Comment by oantolin** [comment]
Great, thanks!

**Pull request merged**
