### PR TITLE
embark-region-map: Add align action

### PR DESCRIPTION
**Pull request by minad**

### CODE REVIEW

**Comment by oantolin** [comment]
I usually find `align-regexp` more useful than `align`. Maybe we should add both?

**Comment by oantolin** [comment]
Although, it could just be ignorance, I've never bothered really configuring align. Maybe if I did I'd be able to use it more often.

**Comment by minad** [comment]
`align` comes already preconfigured with a set of regexps. I think it is good to have here, also for discoverability. Maybe people will use it more often then ;)

**Comment by oantolin** [comment]
Well, let's definitely add `align`. But maybe also `align-regexp` is worth adding.

**Comment by oantolin** [comment]
Align comes with a ton of rules! I wonder if any of them does something I'd be interested in...

**Comment by oantolin** [comment]
Oh, looking at the value in a customize buffer makes it much easier to understand.

**Pull request merged**
