### PR TITLE
Update docstring for `embark-bindings-at-point' in embark.el

### PR DESCRIPTION
**Pull request by sympodius**
Escape single quotes in docstring for `Stash'

### CODE REVIEW

**Comment by oantolin** [comment]
Why did you want to make this change?

**Comment by minad** [comment]
Because the bytecode compiler started to complain about single quotes for no good reason.

**Comment by oantolin** [comment]
Oh, I'm still safe from that new bytecompiler warning here in 28.2-land. :) I guess the semantically correct fix is to either drop the quotes (and lowercase stash) or use double quotes, then.  I'll drop the quotes. cf5f25a22f91d7ed33f582feec7a2e71d766fc61

**Comment by minad** [comment]
I moved to Emacs 29 not too long ago. It works quite well since the branch has been mostly frozen. :)

**Comment by sympodius** [comment]
> Because the bytecode compiler started to complain about single quotes for no good reason.

Yeah, this was the reason. And you are quite right, @oantolin ; my suggestion to use the backtick-single-quote combination would have been semantically incorrect. You and @minad continue to do great work :)

**Pull request closed without merging**
