### PR TITLE
Ensure that expression actions work for defuns

### PR DESCRIPTION
**Pull request by minad**
Do you have some odd whitespace setting btw?

Please check if you think it is correct to do it like this.

### CODE REVIEW

**Comment by minad** [comment]
Oh, this should also be adjusted to your changes in https://github.com/oantolin/embark/commit/37aa15d201cfd9b90a869da1d2b65a5322a203c2.

**Comment by oantolin** [comment]
I don't think it's correct. If point is on the `f` of `(defun ...)`, wouldn't you just move it one character to `e`?

**Comment by minad** [comment]
The point will be on the first character of `defun`.

**Comment by oantolin** [comment]
I'm very confused:

1. `backward-char` would move you to `e`, no?
2. Even if you do get moved to `d` as you say, that's still not enough: you want to move to the `(`.

**Comment by oantolin** [comment]
Also, I have no idea how I wind up with that extra whitespace. :(

**Comment by minad** [comment]
You missed the `(goto-char (car (bounds-of-thing-at-point 'sexp)))` right before the parenthesis check.

**Comment by oantolin** [comment]
> You missed the `(goto-char (car (bounds-of-thing-at-point 'sexp)))` right before the parenthesis check.

I could have sworn that line was in red. 😛 Sorry about the confusion.

**Pull request merged**
