### PR TITLE
Add embark-selection-indicator (See #629)

### PR DESCRIPTION
**Pull request by minad**
The mode line indicator proposed in https://github.com/oantolin/embark/issues/629#issuecomment-1529483532.

### CODE REVIEW

**Comment by oantolin** [comment]
Thanks for doing this!

I haven't tested the code yet, but here are my initial reactions:

1. Didn't you run into some problem by using literal fontified strings once? Something to do with byte compilation, I think.

2. I like using `embark-selection-indicator` as both a boolean and a format string!

3. This updates the mode line after each individual item is deselected. When doing `C-. A SPC` to deselect all candidates, I wonder if maybe that's too much updating. Have you tried? Do you see a visible count down?

4. I don't have much experience with the mode line, but I do remember you aren't supposed to do anything expensive in an `:eval`. I think this is probably fine, but I think best practice is supposed to be to just have a global variable you write to, so that `:eval` only does a variable lookup.

**Comment by minad** [comment]
1. Yes, in native compilation in an Emacs 28 development version. This has been fixed a long time ago. I use propertied strings at many places in my packages.

3. force-mode-line-update just sets a variable. It doesn't redisplay. See the C source.

4. Yes. I think this should be fine. We could save the string formatting, but formatting a single string should be cheap enough. We need the buffer local lookup in any case such that the active minibuffer is taken into account (We could change the message to EmbarkMinibuffer in that case. Do we want that?).

**Comment by oantolin** [comment]
Great! I think this looks pretty good then. I'll test drive it a bit to see if it feels confusing going from a buffer with a selection to a minibuffer with a selection, but my initial feeling is that this is fine as is, that we don't need to change the message to EmbarkMinibuffer.

**Comment by oantolin** [comment]
Thank you!

**Pull request merged**
