### PR TITLE
Unzebra

### PR DESCRIPTION
**Pull request by minad**
Just opening this such that the discussion in #593 does not get lost. Remove the zebra and the (almost useless) embark-collect-revert-hook. Given how much code space the Zebra needs, I don't think it is justified to keep it in captivity in our zoo. As alternative I suggest a meerkat mode. Also "fixes" #164 .

### CODE REVIEW

**Comment by minad** [comment]
No sympathy for meerkats? :cat2:

**Comment by oantolin** [comment]
I wonder if an outright removal is best. Maybe I should go with obsoletion warnings first.

**Comment by minad** [comment]
Obsoletions are generally more user friendly, however I always wonder about their visibility. If you enable obsolete zebra you won't notice anything in most cases.

**Comment by oantolin** [comment]
I decided to bite the bullet and just remove it. If I had to bet, I'd bet nobody even notices.

**Pull request merged**
