### PR TITLE
Integration nitpicks

### PR DESCRIPTION
**Pull request by minad**
- Make the functions private. I argue that the integration code is an internal detail.
- Don't use bound-and-true-p

You may want to pull this or you may want to push your own version ;)

### CODE REVIEW

**Comment by oantolin** [comment]
So integration with "incompatible completion systems" should be private, but it's OK to keep the integration with default completion and icomplete  (which is compatible in the sense that it doesn't need separate functions) public? I guess that's sort of reasonable.

**Comment by minad** [comment]
Ops, sorry. Icomplete and default should also be private.

**Comment by minad** [comment]
But well, they are already in the default list somehow. I don't know :shrug:

**Comment by oantolin** [comment]
But then integration with completion UIs would be private and all others target finders public, that sounds weird too. You don't want all the target finder to be private, do you?

**Comment by oantolin** [comment]
I think I now agree with making the integration with incompatible completion UIs private, and keeping integration with built-in Emacs features public. I'll merge.

**Comment by minad** [comment]
I object to the notion of an "incompatible completion UI" for Vertico. I claim full compatibility! :grin:

**Comment by oantolin** [comment]
Well, obviously I say "incompatible" tongue in cheek. But for purposes of Embark, Vertico is "incompatible" in that the minibuffer contents and location of point are not the entire state, it has "hidden" state in the selection index.

**Comment by minad** [comment]
Yes, that is right. It is also not using the `completion-all-sorted-completions` state. I had actually considered using that and performing the rotations like Icomplete is doing and just replacing the UI, but I guess this would have resulted in a more brittle and more complicated code base. And we already have Icomplete/Icomplete-vertical. For these reasons I think it was the right decision to implement it as I have it. Since the other minibuffer state does not interfere with Vertico you can use all the `minibuffer-complete` commands as usual (see https://github.com/minad/vertico#keymap).

**Comment by oantolin** [comment]
I think Vertico is great as is, please don't take my "incompatible" joke seriously.

**Comment by minad** [comment]
Thanks, I understood how you meant it :)

**Pull request merged**
