### PR TITLE
Keep indicator alive when cycling

### PR DESCRIPTION
**Pull request by minad**
This is important for the vindicator which appears after some time. It should
not close when cycling.

WARNING: The indicator calling convention is changed again. I wouldn't guarantee that
it is the last time, so we should document that writing custom indicators is
currently an unstable feature.

As discussed in #310, https://github.com/oantolin/embark/issues/310#issuecomment-890003547

### CODE REVIEW

**Comment by oantolin** [comment]
I merged the new master in, correctly, I hope. After testing I'm not so sure about this... It basically forbids resizing to fit the contents while cycling.

**Comment by minad** [comment]
I don't use it with the fixed size, I use the reuse window configuration. But there shouldn't be a problem to resize the window to the fit the buffer after update?

I am quite sure that this is a good change since it results in a UI which flickers much less when cycling. I find this quite annoying. The resizing problem should be fixable?

**Comment by oantolin** [comment]
I guess there should be a way to reapply the window parameters from the display buffer list.

**Comment by minad** [comment]
Not sure if this is the correct way (probably not):

~~~
        (when indicator-window
          (bury-buffer embark--verbose-indicator-buffer))
        (setq indicator-window
              (let ((display-buffer-alist
                     `(,@display-buffer-alist
                       (,(regexp-quote embark--verbose-indicator-buffer)
                        ,@embark-verbose-indicator-display-action))))
                (display-buffer embark--verbose-indicator-buffer)))))))
~~~

But it resizes the window.

**Comment by minad** [comment]
We can even simplify the function:

~~~ elisp
(defun embark-verbose-indicator ()
  "Indicator that displays a list of available key bindings."
  (lambda (&optional keymap targets prefix)
    (if (not keymap)
        (when-let ((win (get-buffer-window embark--verbose-indicator-buffer
                                           'visible)))
          (quit-window 'kill-buffer win))
      (embark--verbose-indicator-update
       (if (and prefix embark-verbose-indicator-nested)
           (lookup-key keymap prefix)
         keymap)
       targets)
      (let ((display-buffer-alist
             `(,@display-buffer-alist
               (,(regexp-quote embark--verbose-indicator-buffer)
                ,@embark-verbose-indicator-display-action))))
        (display-buffer embark--verbose-indicator-buffer)))))
~~~

**Comment by minad** [comment]
I pushed the update.

**Comment by oantolin** [comment]
I had inlined the `embark--verbose-indicator-buffer` variable, mostly because it was used before it was declared and its name is longer than the value. Did you reintroduce it? (Which is fine, but move the declaration to before the first use.)

**Comment by minad** [comment]
Sorry, I got tripped up by this change. See my official complaint here https://github.com/oantolin/embark/commit/75b6d56b495e4d42d6f9fae86b4e537488cce692#commitcomment-54218707 ;)

**Comment by minad** [comment]
But to be clear, the last force pushed commit uses string literals everywhere for the buffer name like you prefer. So it should work now.

**Comment by oantolin** [comment]
I don't really prefer the string literal. A variable is fine, but I do mind the compiler warnings, so if you want to use a variable make sure it's defined before the first use.

**Comment by minad** [comment]
The last commit reintroduces the variable, in case you reconsider 75b6d56.

**Comment by oantolin** [comment]
Yes, let's keep the variable.

**Comment by oantolin** [comment]
Thanks for doing this. It does feel smoother.

**Comment by minad** [comment]
Thanks for reworking the code and checking it thoroughly!

**Pull request merged**
