### PR TITLE
Marking candidates

### PR DESCRIPTION
**Pull request by minad**
See the discussion in #166

### CODE REVIEW

**Comment by minad** [comment]
@oantolin Can we merge #466 before proceeding on this one?

**Comment by minad** [comment]
> Sure, but it'll take me a couple of days to get to this probably.

There is no hurry here! I just think it is better to do a bit of cleanup first before we add new features, see also #468.

**Comment by oantolin** [comment]
I've implemented the simplified embark-collect & embark-live now.

**Comment by oantolin** [comment]
I'm going to take this code and update it for the recent changes.

**Comment by oantolin** [comment]
Done. 6a8e6ded2da3e4bc9672aefe956c0f13e625cab2

I added toggle-marks and unmark-all commands as well.

**Comment by minad** [comment]
Great, thanks! How did you address this comments about moving the overlays when toggling the view modes?

> ;; TODO Do we need this variable?
;; Also add a list of marked candidates, or a list of overlays?
;; When switching the display modes we have to move the overlays too.
;; We could also turn this variable into an alist, with value=marked.

**Comment by oantolin** [comment]
I did not address it all. 🙄 The marks just vanish. 🤣

**Comment by oantolin** [comment]
I created issue #473 so I don't forget to fix this.

**Comment by bdarcus** [comment]
Where would you like feedback, or possibly dumb questions, @oantolin? Here?

**Comment by oantolin** [comment]
Here would be fine, @bdarcus.

**Comment by bdarcus** [comment]
OK, so I tested this on my obvious use case: inserting multiple citations.

So I added `org-cite-insert` to `embark-multitarget-actions`, and then:

1. narrowed completions
2. ran embark-collect
3. marked two candidates
4. ran embart-act-all

... and here's where I got stuck.

I think ideally embark would just run the command.

But it doesn't; it prompts if I want to run it. If I do, it still doesn't actually do so, and prompts again.

In the end, I can't get a result, and find it all confusing at this point.

Am I doing something wrong?

And did you add an option to not prompt? I recall we discussed this earlier.

**Comment by bdarcus** [comment]
Also, how would you two imagine keybindings for mark/unmark?

I had been wondering about `SPC` for both, but I guess, notwithstanding the question of whether that's a good idea, that's currently not possible since there's no `embark-collect-toggle-mark` (there is a "toggle-marks" command, but that applies to all candidates in the collect buffer)?

**Comment by oantolin** [comment]
Oh, I try to not invent key bindings if I can avoid it: I just copied copied dired and ibuffer, mark is `m`, unmark is `u`, toggle everything is `t`, unmark everything is `U`. That's what I imagine Emacs user already have muscle memory for.

**Comment by bdarcus** [comment]
> Oh, I try to not invent key bindings if I can avoid it: I just copied copied dired and ibuffer, mark is `m`, unmark is `u`, toggle everything is `t`, unmark everything is `U`. That's what I imagine Emacs user already have muscle memory for.

Ah right; makes total sense!

**Comment by bdarcus** [comment]
> > So I added `org-cite-insert` to `embark-multitarget-actions`
> 
> I think this shouldn't work, because that tells Embark to call the functions with a list of candidates, and `org-cite-insert` does not take a list as an argument.

OK. I need to think about that some more.

But if I do `citar-insert-citation` instead, I do get a result closer to expectation, but it's not the key that gets inserted, but the whole candidates. 

I don't recall seeing anything like that with `embark-act-all` earlier.

**Comment by oantolin** [comment]
This seems to work if you have `org-cite-insert-processor` set to `basic`:

```elisp
(defun cite-all (refs)
  (interactive)
  (cl-letf (((symbol-function #'org-cite-basic--complete-key)
             (lambda (&optional _)
               (let ((tbl (org-cite-basic--key-completion-table)))
                 (mapcar (lambda (ref) (gethash ref tbl)) refs)))))
    (org-cite-insert nil)))

(add-to-list 'embark-multitarget-actions 'cite-all)
```

**Pull request closed without merging**
