### PR TITLE
Profile

### PR DESCRIPTION
**Pull request by minad**

### CODE REVIEW

**Comment by oantolin** [comment]
😮 There's a second profiler in Emacs I completely forgot about!

**Comment by minad** [comment]
Yes, I've learned about it by @dgutov in his Emacs conf talk! I didn't know about elp before.

**Comment by oantolin** [comment]
> Yes, I've learned about it by @dgutov in his Emacs conf talk! I didn't know about elp before.

I could remember where I learned about it, but it was also from that talk. So I've only known about it a short while.

**Comment by oantolin** [comment]
Why did you pick `%` for the binding?

**Comment by minad** [comment]
Hmm, does not make so much sense for an instrumenting profiler. Feel free to change it to something else - a letter.

**Comment by minad** [comment]
Omar, I changed the keybinding to "s" and "S" in https://github.com/oantolin/embark/pull/417/commits/55cf25713ab9974f0a629d6f1ae459a7309b8a2d.

**Pull request merged**
