### PR TITLE
Rename embark-default-action to embark-dwim

### PR DESCRIPTION
**Pull request by minad**
As discussed in #237

### CODE REVIEW

**Comment by oantolin** [comment]
I hadn't remembered until just now, but `C-.` is a suboptimal binding for `embark-act` because icomplete uses it to cycle among completions! (It's bound to `icomplete-forward-completions` in `icomplete-minibuffer-map`. If we really want to recommend that binding, we'll need a note for icomplete users.

**Comment by oantolin** [comment]
I think we should probably just recommend a different binding. I don't want to recommend using what is probably an important default key bindings for icomplete users. (Shadowing `M-.` is very different, since at least `embark-dwim` is a generalization of the default binding.)

**Comment by minad** [comment]
Oh okay, I wasn't aware of that icomplete binding. I always configure Icomplete to use the movement keys for rotation, similar to vertico.

**Comment by oantolin** [comment]
Me too, which is why I forgot that keybinding until now.

**Comment by minad** [comment]
One more nitpick - M-. is not an exact generalization, since the xref command works also if there is no symbol at point. Therefore one may still keep the xref commandbound somewhere. For me C/M-. work well at least.

**Comment by minad** [comment]
@oantolin I added another simplification commit, is there a reason why embark--target returns `(nil nil nil)` when no target is found. This is not exactly intuitive ;)

**Comment by oantolin** [comment]
You are mixing a lot of unrelated changes here. So it'll take me a while to evaluate the PR as a whole. I think the embark-dwim changes are ready to merge as is. The key binding docs I'll need to change to something that doesn't clash with icomplete (since I don't want bug reports claiming that `embark-act` does nothing but cycle the completion candidates :P). And you last change I'll have to think about. Most places where `embark--target` is called destructure the value. I don't know if `nil` will raise an error or not, maybe we need `(nil nil)` --we certainly don't need `(nil nil nil)`.

**Comment by minad** [comment]
No, the destructuring does not raise an error.

~~~ elisp
(pcase-let ((`(,x . ,y) nil))
  nil)
~~~

But I am bailing out early with `(or ... (user-error ...))`. Of course one can also rewrite this as a simple `pcase`. But I would really like to see `embark--target` returning plain nil if no target is found.

**Comment by oantolin** [comment]
I'm slow. I'll have to think a bit about whether it is OK for `embark--target` to return `nil`. It isn't designed too, but maybe it can return `nil` with no complications.

**Comment by minad** [comment]
> I'll have to think a bit about whether it is OK for embark--target to return nil.

I looked at all the call sites, there are only three or. They are all okay with `embark--target` returning nil. But please give it another cross check.

Sorry for mixing the unrelated changes. I just stumbled upon this when I wrote this `dm-embark-dwim` command.

~~~ elisp
  (defun dm-embark-dwim (&optional arg)
    (interactive "P")
    (if (or arg (not (embark--target))) ;; NOTE: Check here if there is an Embark target!
        (call-interactively #'xref-find-definitions)
      (embark-default-action)))
~~~

**Comment by oantolin** [comment]
Sorry, I think I just panicked! 😄 It is indeed easy to check that `embark--target` is allowed to return `nil`.

**Comment by oantolin** [comment]
I have to say though, that `(pcase-let ((`(,a ,b ,c) nil)) (list a b c))` returning `(nil nil nil)` feels like a bug in `pcase-let` and I'm worried that Emacs might fix it at some point. 😛

**Comment by minad** [comment]
> Sorry, I think I just panicked!

Usually I try to avoid such unrelated changes. But in some case when looking at something it occurs that one finds some small inconsistency or weirdness as in this case which can be improved quickly - like some on the fly code review. I have no intention of doing a huge overhaul here :)

> I have to say though, that (pcase-let (((,a ,b ,c) nil)) (list a b c))returning(nil nil nil)feels like a bug inpcase-let` and I'm worried that Emacs might fix it at some point.

Agree. But note that I am not using this here, since I am bailing out early with the user-error. Should be all good in any case. I was also wondering about the pcase desugaring and checked what it does.

**Comment by oantolin** [comment]
> Agree. But note that I am not using the nil pcase-let here, since I am bailing out early with the user-error. Should be all good in any case.

Yes, of course. I wrote that before realizing you also changed `embark-act`. I like the `(or (thing) (user-error "boom"))` idiom better that what was there before. It would be even better with `(defalias 'die 'user-error)`, like Perl.

**Pull request merged**
