### PR TITLE
Implement multiple targets at point (Fix #92)

### LINKED ISSUE #92: Inability to consider current context as matching multiple target types
I would be able to use Embark as a general context-dependent way to execute actions. This may mean that several things may be relevant in the current context (and thus several keymaps may apply). Currently, only the first matching target is taken into account.

Why do I want to do this? For example, there may be simultaneously 1. a flymake error at point to deal with and 2. a symbol whose definition can be looked up.  Another use-case would be to handle all xref-identifiers uniformly (do `xref-find-definition` on the identifier at point), which currently with the elisp symbol definition (which is only valid in elisp contexts, but offers a wider set of actions).

Do you think that the scope of Embark can be widened to support this sort of use-case? Perhaps there is another package which is more suitable for this?

### PR DESCRIPTION
**Pull request by minad**
When not acting in the minibuffer all target finders are executed. The action
indicator will then indicate that multiple targets exist. By pressing the
`embark-act` key again, the user can cycle to the next target.

The alternative approach discussed in #92 was to merge the keymaps. This
approach has disadvantages: Multiple targets are active at the same time and
depending on the selected action, the target is selected. This complicates the
current `embark--act` implementation, which is untouched by this PR. Furthermore
keybindings are shadowed, which makes the individual keymaps a lot less useful.
This shadowing will lead to confusion and it will not be obvious to the user
which target is actually being used.

The current approach is also easy to implement, it fits well within the existing
codebase. This is a good indication to go this route.

### CODE REVIEW

**Comment by minad** [comment]
@oantolin I just saw that you had an initial implementation with the keymaps merged (https://github.com/oantolin/embark/commit/73a4c6248c30a86f221adbc440e4871897379c57). There is another disadvantage of that approach I forgot to mention above - since multiple targets are active at the same time, you cannot execute M-x on the mixtarget.

**Comment by jaor** [comment]
On Sat, Jul 24 2021, Daniel Mendler wrote:

> When not acting in the minibuffer all target finders are executed. The action
> indicator will then indicate that multiple targets exist. By pressing the
> embark-act key again, the user can cycle to the next target.

apologies if this has already been discussed, but how do user-defined
action indicators fit in this picture? do they receive a list of keymaps
and a list of targets?

**Comment by minad** [comment]
@jaor User defined indicators receive the keymap of the current target and a list of all `(type.target)` pairs. The first element of the list will be the current target. When the user cycles between the targets a new action indicator will be created and destroyed every time.

**Comment by jaor** [comment]
On Sat, Jul 24 2021, Daniel Mendler wrote:

> @jaor User defined indicators receive the keymap of the current target
> and a list of all (type.target) pairs.  The first element of the list
> will be the current target. When the user cycles between the targets a
> new action indicator will be created and destroyed every time.

I see, that works nicely.  Just curious here: why calling with a list to
type/target if only a keymap is sent? Wouldn't it be simpler to call
with just keymap type and target?

**Comment by minad** [comment]
> I see, that works nicely.  Just curious here: why calling with a list to
type/target if only a keymap is sent? Wouldn't it be simpler to call
with just keymap type and target?

The idea is that the action indicator should have the possibility to indicate that other shadowed targets exist. The indicator can show the current target, its keymap and a list of alternative targets, which can be reached by cycling.

(I've seen that your action indicator has been mentioned in a discussion on reddit. Maybe it would be a good addition to Embark?)

**Comment by oantolin** [comment]
This is a brilliant, @minad! I really wanted common cases to require no further keypresses, and this cycling idea achieves this if we can order the target finders carefully, prioritizing the type whose actions are most commonly needed.

It was important to me that whatever UI was chosen was composable in the sense you describe: that you can add new targets and keymaps without worrying about shadowing. I thought that maybe the only practical way to achieve that was to make embark-act a two-stage processes: first show a menu of targets and once the user picks one go through the standard embark-act process. But the menu of targets works against the idea of common cases taking no more keystrokes than currently, and also it seemed like presenting the menu would need a pop-up or enlarging the minibuffer, which I prefer to avoid (I know I'm weird about that and most people like huge minibuffers like you get with Vertico, Selectrum or Which-key).

But, as long as not too many targets are found at the same location, I think this cycling idea is pretty good. I hate cycling among 5 things, I love cycling between 2 things. I think 3 is OK and 4 is tolerable. (I know because I've tried all those values for `completion-cycle-threshold` :P.) I guess we can refine the target finders to keep the average number of targets small (and they're probably already pretty much there). I guess we can always add later a command that prompts for a target and cycles immediately to it.

Also, as you say we can have the sexp and defun target finders trigger anywhere in the corresponding region to get an expand-region like effect.

**Comment by minad** [comment]
> This is brilliant, @minad! I really wanted common cases to require no further keypresses, and this cycling idea achieves this if we can order the target finders carefully, prioritizing the type whose actions are most commonly needed.

Thanks, I am glad you like it!

> (I know I'm weird about that and most people like huge minibuffers like you get with Vertico, Selectrum or Which-key).

Maybe I should try setting vertico-count to 3 ;)

> But, as long as not too many targets are found at the same location, I think this cycling idea is pretty good. I hate cycling among 5 things, I love cycling between 2 things. I think 3 is OK and 4 is tolerable.
> I guess we can always add later a command that prompts for a target and cycles immediately to it.

I don't think we won't get significantly more than 3 targets at point. But if that would happen there is also a good solution, we could add a prefix argument to `embark-cycle` which lets you jump to the right candidate right away or as you say add a separate command bound to some special jumping keys `# 1`, `# 2`, ...

At least the solution here can potentially scale. Good luck with merging keymaps if you have 5 possible targets at point.

Please let me know if there are things that should be addressed. For stylistic changes I guess you are faster to do it yourself, like changing mapcars and friends to cl-loop :)

**Comment by minad** [comment]
> ...we can order the target finders carefully, prioritizing the type whose actions are most commonly needed.

One possibility I want to point out - we can even add multiple target finders with different priorities returning the same type and target. This allows for very fine-grained tuning. See also my comment in `embark--targets`.

**Comment by oantolin** [comment]
I'm trying it out and loving it!

Here are a few minor quick impressions:

1. I think the default indicator should probably have the shadowed types come after the target, it feels weird to have the type and target separated by anything other than whitespace. Maybe `type 'target' (… shadowed)`?

2. The default target finders will need a little tweaking and reordering, but are already pretty good as is!

3. When you use the default `nil` setting of `embark-cycle-key` with the completing-read prompter, the single target case can be jarring: if you repeat the `embark-act` keybinding you get multiple nested `embark-act`s.

**Comment by minad** [comment]
> I think the default indicator should probably have the shadowed types come after the target, it feels weird to have the type and target separated by anything other than whitespace. Maybe type 'target' (… shadowed)?

I did it like this since then the target position does not jump when cycling, but maybe your formatting is easier to understand?

~~~
symbol(defun) targetsym
defun(symbol) targetdefun
~~~

I am not sure which one I prefer.

~~~
Act on "target" type (shadowed)
Act on type(shadowed) "target"
Act on type "target" (shadowed)
~~~

But this tweaking can also come later. Since we are modifying the action indicator right now, I thought that the current code could also be a bit cleaned up in a separate PR. Make `embark-action-indicator` obsolete and use functions for everything.

~~~ elisp
(defvar embark-action-indicator-function #'embark-default-action-indicator)
(defvar embark-default-action-indicator-format ("%s...))
~~~

> When you use the default nil setting of embark-cycle-key with the completing-read prompter, the single target case can be jarring: if you repeat the embark-act keybinding you get multiple nested embark-acts.

Yes, but this has already been the case? This is when you act on the binding candidate itself. We could decide to always bind `embark-cycle` in the completing read prompter and if there is only a single candidate, print a message.

**Comment by jaor** [comment]
On Sat, Jul 24 2021, Daniel Mendler wrote:

> The idea is that the action indicator should have the possibility to
> indicate that other shadowed targets exist. The indicator can show the
> current target, its keymap and a list of alternative targets, which
> can be reached by cycling.

Aha, that makes sense.  I don't have a very concrete use case here, but
i am thinking that receiving the full list of keymaps (together with
types and targets) could be considered: imagine i want to hack an
indicator that uses transient or hydras and that itself provides access
to the other keymaps (not necessarily in cycling order), or something of
the sort... thinking out loud here...

> (I've seen that your action indicator has been mentioned in a
> discussion on reddit. Maybe it would be a good addition to Embark?)

i'd be happy to send a PR if you guys think it's worth it... it might
have some rough edge, but i guess we could refine it as needed.  Or add
it to some wiki or the other.

**Comment by oantolin** [comment]
> Make `embark-action-indicator` obsolete and use functions for everything.

That probably would be simpler. Good idea.

> But this tweaking can also come later.

Agreed.

> Yes, but this has already been the case? This is when you act on the binding candidate itself.

Yes, of course. It just never bothered me before because I never had a reason to press the embark-act key twice in a row. :) I'm not saying anything needs to be done about this, just pointing it out.

**Comment by minad** [comment]
> Yes, of course. It just never bothered me before because I never had a reason to press the embark-act key twice in a row. :) I'm not saying anything needs to be done about this, just pointing it out.

Fixed in https://github.com/oantolin/embark/pull/278/commits/46e68abfdc1f61e7a2d2a0db3b2dca1d1c540b46

**Comment by oantolin** [comment]
@jaor I would love a pull request with an indicator like that, I'd probably make it the default too (but most likely wouldn't use it myself, I don't like "always on" reminders, preferring to summon them when I need them). When I saw a screenshot I do remember thinking that it would make sense to rewrite it to create an Embark collect buffer, since you wouldn't have to do any layout by hand and also would get the possibility of toggling to grid view for free (which looks a lot like which-key, in fact).

**Comment by minad** [comment]
> When I saw a screenshot I do remember thinking that it would make sense to rewrite it to create an Embark collect buffer, since you wouldn't have to do any layout by hand and also would get the possibility of toggling to grid view for free (which looks a lot like which-key, in fact).

This would be kind of meta :)

**Comment by oantolin** [comment]
> Fixed in [46e68ab](https://github.com/oantolin/embark/commit/46e68abfdc1f61e7a2d2a0db3b2dca1d1c540b46)

Well, now how do I act on the completion candidates? 😆  You've never used goto definition on an action from the completing-read prompter? 😉

> Regarding the embark-action-indicator, we can do this in a separate PR.

Yes, of course. I wasn't suggesting to do it here.

**Comment by oantolin** [comment]
Actually `embark-act` does seem to work in the completing-read prompter. Weird, I'd never noticed that before.

**Comment by oantolin** [comment]
And, just to be explicit, I was kidding earlier I think the message in 46e68ab is a better default.

**Comment by minad** [comment]
@jaor 

> ...receiving the full list of keymaps (together with
types and targets) could be considered: imagine i want to hack an
indicator that uses transient or hydras and that itself provides access
to the other keymaps (not necessarily in cycling order), or something of
the sort... thinking out loud here...

This is not really possible since only one target is active at a time. In other words, the action indicator and not even the prompter should take control over the keymaps. But we can still reconsider this later. We will probably rework the action indicator later a bit.

@oantolin 

> Well, now how do I act on the completion candidates? laughing You've never used goto definition on an action from the completing-read prompter? wink

M-x :D

**Comment by oantolin** [comment]
So, I'd be delighted to merge now after kicking the tires. Anything else you wanted to do before I merged, @minad?

**Comment by minad** [comment]
From my side it is ready, I added these two PRs (1. adding the message, 2. rename the with-indicator to more meaningful embark--prompt). But overall it seems ready from my side!

**Comment by oantolin** [comment]
Fantastic! Thanks so much, @minad.

**Comment by oantolin** [comment]
I'll play around with it a couple of days, maybe refine or reorder some target finders and then bump the version number.

**Comment by minad** [comment]
Sounds good! Maybe also experiment with broadening/simplifying some of the target finders, e.g., the expression and defun finder as we discussed?

**Comment by oantolin** [comment]
Yes. I think I'd prefer to have those apply everywhere in their regions and move them toward the end.

As you pointed in the comment out one could also add a copy the defun matching only `.*def.*` with higher priority, but I don't think that's necessary.

I think I'll also tighten the file target so it doesn't trigger on web urls. It gives a silly tramp style `/https:/github.com/oantolin/embark` that doesn't actually seem to work as a path.

**Comment by oantolin** [comment]
Oh, and the sexp target finder should not match defuns, since the defun keymap already inherits from the sexp keymap.

**Comment by minad** [comment]
> Oh, and the sexp target finder should not match defuns, since the defun keymap already inherits from the sexp keymap.

Probably both should be replaced by a single finder+refinement, like for the identifiers?

**Comment by oantolin** [comment]
> Probably both should be replaced by a single finder+refinement, like for the identifiers?

No, I think that if I'm somewhere in the middle of a function, I'd like to be able to act on the smallest containing list `(...)` and also on the whole defun.

**Comment by oantolin** [comment]
> Generally, false positives in the low priority filters are a problem now unfortunately. But it should be possible to tighten all these finders.

I think they're not really that many. I bet almost all come out in the next couple of days.

**Comment by minad** [comment]
> I'd like to be able to act on the smallest containing list (...) and also on the whole defun.

Yes this is the behavior I would like to have.

**Pull request merged**
