### PR TITLE
Add tips for Vertico users to get which-key like behaviour

### PR DESCRIPTION
**Pull request by richcarl**
Tried to summarize the conclusions from #707 in a form that would be helpful to others.

### CODE REVIEW

**Comment by oantolin** [comment]
Thank you for this! I probably should have added something like this to the documentation a while ago, but I guess I needed some more external validation that this is a good configuration to recommend. 😛

I'll proof read and check it's in the best location within the documentation before merging, probably this evening.

**Comment by richcarl** [comment]
Glad to be able to contribute a little!

**Comment by minad** [comment]
I also like this setup with grid mode :)

**Comment by oantolin** [comment]
Hi @richcarl. I thought some of the information you added really belonged to different sections so I moved some stuff around (and added some new stuff too, on `embark-bindings`). What do you think?

**Comment by richcarl** [comment]
Looks great!

**Comment by oantolin** [comment]
Merging, then. Thanks again for getting the ball rolling on this!

**Pull request merged**
