### PR TITLE
add bookmark actions

### PR DESCRIPTION
**Pull request by minad**
See #54

### CODE REVIEW

**Comment by oantolin** [comment]
We should add jump, jump-other-window (maybe even jump-other-frame) and relocate, possibly set too.

**Comment by oantolin** [comment]
Oh, and bookmark-insert shadows the general insert command. Since they do different things, it probably makes sense to have both. In the package keymap I bound the general insert command to `I`, we can do the same thing here.

**Comment by oantolin** [comment]
I'll merge and add those.

**Comment by minad** [comment]
> Oh, and bookmark-insert shadows the general insert command. Since they do different things, it probably makes sense to have both. In the package keymap I bound the general insert command to I, we can do the same thing here.

I think I fixed this.

**Comment by oantolin** [comment]
Don't worry, I'll push those changes in a minute. Thanks for the PR!

**Comment by oantolin** [comment]
Done, 9bdbfc40e6f35254be19b3b2bc5230e08b6dc1de.

**Comment by oantolin** [comment]
Huh, the other window and other frame commands were popping up a mouse menu! I fixed that too: d7a89eb2b797e551030989de74634372ddae37c0

**Pull request merged**
