### PR TITLE
embark-consult--strip-prefix: use consult--tofu-char

### PR DESCRIPTION
**Pull request by minad**
+ minor docstring corrects to make package lint happy

### CODE REVIEW

**Comment by oantolin** [comment]
Funny, I could have sworn I did use consult--tofu-char

**Comment by minad** [comment]
Yes you used it at another place.

**Comment by oantolin** [comment]
Ah, that must be it. Thanks for spotting this one.

**Comment by minad** [comment]
It just occurred to me that this function can even go away since the transformer has access to text properties. This means we can strip the consult-location property and the invisible property in the case of consult-isearch. Maybe that would be preferable?

**Comment by oantolin** [comment]
Oh, you mean, change the transformer so instead of looking for initial tofu it looks specifically for characters with either a `consult-location` or `invisible` property? I guess that's a little better. Make the property names part of the API instead of reserving a chunk of unicode as part of the API.

**Comment by oantolin** [comment]
Is this what you had in mind, @minad? 34e9070140f63627929a88503659fe82bef75d46

**Pull request merged**
