### PR TITLE
Further simplification of embark--action-keymap

### PR DESCRIPTION
**Pull request by minad**
* Get rid of the overriding-keymap, why is it needed? In order to
  override one can also advise embark--action-keymap.
* Do not use embark-general-map by default, generalize.

(Further simplifications regarding to #258)

### CODE REVIEW

**Comment by minad** [comment]
Note that the export function override is redundant. Is there a point in keeping this variable? Embark already has many customization variables and here we can cut it a bit down without downsides.

**Comment by minad** [comment]
Hmm, it seems @clemera introduced both these variables in https://github.com/oantolin/embark/pull/37. I am essentially reverting this PR here. @clemera argued that the overrides simplify the overriding and the amount of work the user of this functionality has to do. Maybe this should be reconsidered? From my point of view it is better to have an easier lookup logic with fewer special casing and fewer customization variables the user has to lookup and understand. What do you think?

**Comment by oantolin** [comment]
> Also in #37 the parent keymap logic has been introduced which turned out to be not flexible enough.

Oh, I didn't realize this. I thought the other issue was just meant to simplify the code.

I think I agree with all your  changes here (of course, _I_ would agree, you're basically going back to how I did things originally), but I worry about breaking people's custom code, at least @clemera's.

**Comment by minad** [comment]
I don't think these variables are used much - I would remove this without a replacement and then fix upcoming issues on a case by case basis. The point is that these variables are entirely redundant.

I found a single use case https://github.com/unhammer/gnus-recent/blob/cc37ab30da76ec8c9e0357006928e21488099945/gnus-recent.el, but this could easily be replaced by modifying the embark-keymap-alist instead, setting only the t key.

**Comment by minad** [comment]
I think https://github.com/oantolin/embark/pull/260/commits/d687aa100218509c20f95e1e1f99b1923d431619 is a satisfactory solution, which gets rid of the override variables, but still allows overriding.

**Comment by oantolin** [comment]
Let's do it, I like simplification. If it causes any trouble at all it would only be for sophisticated users who can easily update their code.

**Pull request merged**
