### PR TITLE
Some readme improvements (Fix #235)

### LINKED ISSUE #235: Document the Embark calling convention in the README
* For commands, the target is injected in the minibuffer
* The target is passed as first argument to unary functions

### PR DESCRIPTION
**Pull request by minad**
https://github.com/oantolin/embark/wiki/How-does-Embark-call-actions%3F also as a PR. I think you should keep the README in your style, therefore I put it in the wiki. So feel free to close or rewrite this as you like. But it would be instructive to have some very simple examples of how these actions are actually called. Also the Embark/Consult/Marginalia section should be updated. The changes happend a while ago, so it is better to describe the status quo.

### CODE REVIEW

**Comment by oantolin** [comment]
I agree with the essence of everything here, I'll just reword some things a bit.

**Comment by oantolin** [comment]
And I just learned I can push changes to your branch! I had no idea.

**Comment by oantolin** [comment]
Thanks again!

**Comment by minad** [comment]
Thanks. Good to have an updated readme :)

**Comment by oantolin** [comment]
It's still lagging behind, but getting there.

**Pull request merged**
